"""Human-in-the-Loop Tools for Agent System"""
from typing import Literal, Any, Optional
from langchain_core.tools import tool
from langgraph.types import interrupt


@tool
def user_interaction(
    type: Literal["story_review", "character_review", "pages_review"],
    intention: Literal["self", "next"],
    prompt: str = "Please review",
    data: Optional[dict[str, Any]] = None
) -> str:
    """
    Trigger HITL interrupt with optional data payload for streaming.

    Args:
        type: Which review component to render in frontend
            - "story_review": Shows enhanced_story + characters (markdown)
            - "character_review": Shows character image grid
            - "pages_review": Shows storybook page viewer

        intention: Routing control
            - "self": Always return to this stage/agent (for minor feedback)
            - "next": If user says "APPROVED", progress to next stage

        prompt: Question/instruction for the user
            Example: "Please review the enhanced story and characters. Approve to continue."

        data: Optional data payload (for story_review, pass enhanced_story and characters)
            Example: {"enhanced_story": "...", "characters": [...]}
            This data will be streamed to frontend as it's generated by LLM

    Returns:
        User's response: "APPROVED" (from approve button) or feedback text
    """
    interrupt_payload = {
        "type": type,
        "intention": intention,
        "prompt": prompt
    }
    if data:
        interrupt_payload["data"] = data

    return interrupt(interrupt_payload)


@tool
def present_enhanced_story(enhanced_story: str, characters: list[dict]) -> dict:
    """
    Present enhanced story to user for review.

    Call this when you have finished enhancing the story and want user approval.
    This tool marks the story as ready for review.

    Args:
        enhanced_story: The enhanced story text with vivid details
        characters: List of character dicts with name and description
            Example: [{"name": "Pip", "description": "A young emperor penguin..."}]

    Returns:
        Confirmation with story metadata
    """
    return {
        "status": "ready_for_review",
        "story_length": len(enhanced_story),
        "character_count": len(characters)
    }


@tool
def escalate(reason: str) -> str:
    """
    Exit current stage and return to orchestrator.

    Call this when user wants to:
    - Change story direction completely
    - Go back to a previous stage
    - Do something outside current stage's scope

    Args:
        reason: Summary of what user wants (helps orchestrator decide)

    Returns:
        Confirmation message
    """
    return f"Escalating to orchestrator: {reason}"
